routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/','HomeController@home');
Route::get('/home','HomeController@home');
Route::get('news','HomeController@news_page');
Route::get('blogs','HomeController@blog_page');
Route::get('contact-us','HomeController@contact_us');
Route::get('news/{id}','HomeController@news');
Route::get('blog/{id}','HomeController@blog');


Route::get('Ccavenue','CCAvenueController@index');
Route::post('Ccavenue','CCAvenueController@Ccavenue');

// Registration and Activation
Route::view('register','home_pages.registration');
Route::post('postregister','RegistrationController@postRegister');
Route::get('activate/{email}/{code}','RegistrationController@activateMail');


// User Login
Route::get('login','LoginController@login');
Route::post('do-user-login','LoginController@vcoinLogin');
Route::get('do-user-logout','LoginController@dologout');

// Forgot Password
Route::get('forgot-password','LoginController@forgot_password');
Route::post('check-email','LoginController@check_email');
Route::get('reset-password/{email}/{token}','LoginController@reset_password');
Route::post('do-reset-password','LoginController@do_reset_password');


// ipn handler
// Route::post('ipn-handler','DepositController@IpnHandler');
Route::get('ipn-handler','DepositController@IpnHandler');
Route::post('withdrawal-handler','UserController@withdrawal_IpnHandler');
// User Routes
Route::group(['middleware' => 'user'],function(){

	Route::get('user-dashboard','DashboardController@user_dashboard');
	//user profile change password
	Route::get('user-profile','ProfileController@user_profile');
	Route::post('update-user-profile','ProfileController@update_user_profile');
	Route::post('change-password','ProfileController@change_password');
	Route::post('profile_update','ProfileController@profile_update');
	//user kyc
	// Route::get('user-kyc','KycController@index');
	// Route::post('user-kyc-upload','KycController@kyc_upload');
	//user wallet
	Route::get('user-wallet','UserController@user_wallet');
	Route::get('deposit/{coin}','DepositController@deposit');
	Route::get('withdraw/{coin}','UserController@withdraw');
	Route::post('do-withdraw','UserController@do_withdraw');
	//deposit bank
	Route::get('deposit-bank','UserController@bankDeposit');
	Route::post('amount-deposit-bank','UserController@amountDepositBank');
	//withdrawal bank
	// Route::get('withdraw-bank','UserController@bankWithdrawal');
	// Route::post('amount-withdrawal-bank','UserController@amountWithdrawalBank');

	// ico / buy-token
	Route::get('buy-token-list','BuyTokenController@icoInformation');
	Route::post('coin-balance','BuyTokenController@coinBalance');
	Route::post('buy-token/{id}','BuyTokenController@buyToken');

	Route::get('ico-information','UserController@ico_information');
	Route::get('network','UserController@network');
	Route::get('getUserDataNetwork','UserController@getUserDataNetwork');
	// buy with paypal
	Route::post('buy-paypal','PaypalController@postPaymentWithpaypal');
	Route::get('success-payment','PaypalController@paymentSucces');
	Route::get('cancel-payment','PaypalController@paymentCancel');
	Route::post('cancel-payment','PaypalController@paymentCancel');
	Route::get('callback','PaypalController@paypalCallback');
	Route::post('currency-price','PaypalController@currencyPrice');
	

});
// User Login

//Route::get('administrator','LoginController@login');
Route::post('do-admin-login','LoginController@dologin');
Route::get('do-admin-logout','LoginController@dologout');

// Admin Routes
Route::group(['middleware' => 'admin'],function(){
	// dashboard
	Route::get('admin-dashboard','DashboardController@admin_dashboard');
	// user manage
	Route::get('user-manage','AdminController@user_manage');
	Route::get('user-status/{id}','AdminController@userStatus');
	Route::get('user-delete/{id}','AdminController@userDelete');
	// profile
	Route::get('admin-profile','ProfileController@user_profile');
	Route::post('update-admin-profile','ProfileController@update_user_profile');
	Route::post('admin-change-password','ProfileController@change_password');
	Route::post('admin-profile-update','ProfileController@profile_update');
	// user kyc approve and regect
	// Route::get('kyc/{id}','AdminController@userKyc');
	// Route::get('kyc-approve/{id}','AdminController@kyc_approve');
	// Route::get('kyc-reject/{id}','AdminController@kyc_reject');
	// history
	Route::get('deposit-history','HistoryController@depositHistory');
	Route::get('withdraw-history','HistoryController@withdrawHistory');
	Route::get('token-history','HistoryController@tokenHistory');
	// setting ico
	Route::get('settings','SettingController@settings');
	Route::post('update-settings','SettingController@update_settings');

	Route::get('phases','PhaseController@phases');
	Route::get('add-phase','PhaseController@add_phase');
	Route::post('do-add-phase','PhaseController@do_add_phase');
	Route::get('edit-phase/{id}','PhaseController@edit_phase');
	Route::post('do-edit-phase','PhaseController@do_edit_phase');
	Route::get('do-delete-phase/{id}','PhaseController@do_delete_phase');
	Route::get('do-active-phase/{id}','PhaseController@do_active_phase');
	// Withdrawal
	Route::get('withdraw-manage','WithdrawalController@withdraw_manage');
	Route::get('withdraw-approval/{id}','WithdrawalController@withdraw_approval');
	Route::get('withdraw-reject/{id}','WithdrawalController@withdraw_reject');
	//withdrawal bank
	// Route::get('withdraw-approval-bank/{id}','WithdrawalController@withdrawBank');
	// Route::post('withdraw-approval-bank/{id}','WithdrawalController@withdrawApproveBank');
	// Route::get('withdraw-reject-bank/{id}','WithdrawalController@withdrawRejectBank');
	//bank
	Route::resource('bank-details','BankDetailsController');
	//deposit bank
	Route::get('deposit-approve-bank/{id}','DepositController@approveddepositBank');
	Route::get('deposit-reject-bank/{id}','DepositController@rejecteddepositBank');



	// News
	Route::resource('news-manage','NewsController');
	Route::resource('blog-manage','BlogController');

});

Route::get('exchange','PaypalController@currency');
//google2fa
Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
Route::post('/2fa/save', 'Google2FAController@saveSecretKey');
Route::post('/2fa/disable', 'Google2FAController@disableTwoFactor');
Route::get('/2fa/validate', 'Auth\AuthController@getValidateToken');
Route::post('/2fa/validate', ['uses' => 'Auth\AuthController@postValidateToken']);
Route::post('/2fa/validate-disabletime', ['uses' => 'Auth\AuthController@postValidateTokenDesable']);
Route::post('2fa/validate-enabletime', 'Auth\AuthController@postValidateTokenenable');

resources/views/admin/add_phase.blade.php
@extends('dashboard_layouts.master')


@section('title') Add New Phase | Vancoin @endsection

@section('style')
    <!-- DatePicker css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/date-picker.css') }}">
@endsection()

@section('content')

<div class="page-body">
    <!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Add New Phase
                        <!-- <small>Vancoin Admin panel</small> -->
                    </h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Add New Phase</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-xl-6">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Phase Information</h5>
                            </div>
                            <form method="post" action="{{ url('do-add-phase') }}" class="theme-form mega-form">
                                {{ csrf_field() }}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="col-form-label">Phase Name</label>
                                        <input type="text" name="phase_name" class="form-control" placeholder="phase name">
                                        @if($errors->has('phase_name'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('phase_name') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label  class="col-form-label">USD Price</label>
                                        <input type="text" name="usd_price" class="form-control" placeholder="Enter price in USD">
                                        @if($errors->has('usd_price'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('usd_price') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Vancoin</label>
                                        <input type="text" name="total_coins" class="form-control" placeholder="enter solding coins">
                                        @if($errors->has('total_coins'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('total_coins') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Bonus</label>
                                        <input type="text" name="bonus" class="form-control" placeholder="bonus coins">
                                        @if($errors->has('bonus'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('bonus') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Start Date</label>

                                        <input type="text" name="start_date" data-language="en" class="form-control datepicker-here digits" aria-describedby="basic-addon2" value="" autocomplete="off">

                                        @if($errors->has('start_date'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('start_date') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">End Date</label>
                                        
                                        <input type="text" name="end_date" data-language="en" class="form-control datepicker-here digits" aria-describedby="basic-addon2" value="" autocomplete="off">

                                        @if($errors->has('end_date'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('end_date') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary">Submit</button>
                                    <a href="{{ url('phases') }}" class="btn btn-danger">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<!--DateTime Picker js-->
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.js') }}"></script>
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.en.js') }}"></script>
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.custom.js') }}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#dashboard-table').DataTable();
} );
</script>
@endsection

resources/views/admin/bank_detalis.blade.php
@extends('dashboard_layouts.master')

@section('title') Deposit Bank | Vancoin @endsection

@section('style')
<style type="text/css" media="screen">
.error {
    margin: 0px!important;
    color: #ff2b2b!important;
}
p {
    font-size: 16px!important;
}   
</style>
@endsection

@section('content')

<div class="page-body">
    <!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Deposit Bank</h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item">Dashboard</li>
                        <li class="breadcrumb-item">Wallet</li>
                        <li class="breadcrumb-item active">Deposit Bank</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row"> 
         @foreach($bank_details as $bank)
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header p-3">
                        <h5 class="card-title">Bank Details</h5>
                    </div>
                    <div class="card-body buy-token">
                        <div class="form-group col-md-12">
                            <label>Bank Name : <strong>{{ $bank->name }}</strong></label>
                        </div>
                        <div class="form-group col-md-12">
                            <label>Account No : <strong>{{ $bank->account_no }}</strong></label>
                        </div>
                        <div class="form-group col-md-12">
                            <label>SWIPT Code : <strong>{{ $bank->swipt_code }}</strong></label>
                        </div>
                        <div class="form-group col-md-12">
                            <label>Bank details show : @if($bank->status == 1)<span class="badge badge-success">Active</span>
                                @elseif($bank->status == 0)<span class="badge badge-danger">Deactive</span>@endif
                            </label>
                        </div>
                        <div class="form-group col-md-12">
                           <a href="{{ route('bank-details.edit',$bank->id) }}" class="btn btn-info pull-right">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        </div>
    </div>

</div>

@endsection

@section('script')
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
$(document).ready(function() {
    $('#deposit').DataTable();
} );

// just for the demos, avoids form submit

$( "#W-form" ).validate({
  rules: {
    amount: {
      required: true,
      digits: true
    }
  }
});
</script>

@endsection

resources/views/admin/bank_detalis_edit.blade.php
@extends('dashboard_layouts.master')

@section('title') Bank Details | Vancoin @endsection

@section('style')
<style type="text/css" media="screen">
.error {
    margin: 0px!important;
    color: #ff2b2b!important;
}
p {
    font-size: 16px!important;
}   
</style>
@endsection

@section('content')

<div class="page-body">
    <!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Bank Details</h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item">Dashboard</li>
                        <li class="breadcrumb-item active">Bank Details</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">  
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header p-3">
                        <h5 class="card-title">Bank Details</h5>
                    </div>
                    <div class="card-body buy-token">
                        <form class="form-horizontal theme-form row" id="W-form" action="{{ route('bank-details.update',$bank_details->id) }}" method="post">

                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}
                            <div class="form-group col-md-12">
                                <label for="paypal_token">Bank Name</label>
                                <input type="text" name="bank_name" class="form-control" autocomplete="off" placeholder="Enter Bank Name" value="{{ $bank_details->name }}">
                                @if($errors->has('bank_name'))
                                    <span class="text-danger">{{$errors->first('bank_name')}}</span>
                                @endif
                            </div>
                            <div class="form-group col-md-12">
                                <label for="paypal_token">Account No</label>
                                <input type="text" name="account_no" class="form-control" value="{{ $bank_details->account_no }}" autocomplete="off" placeholder="Enter Account No" maxlength="25">
                                @if($errors->has('account_no'))
                                    <span class="text-danger">{{$errors->first('account_no')}}</span>
                                @endif
                                <br>
                                <span class="max-min-tokens"></span>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="currency_price">SWIPT Code</label>
                                <input type="text" name="swipt_code" class="form-control" value="{{ $bank_details->swipt_code }}" id="swipt_code" placeholder="Enter SWIPT Code">
                                @if($errors->has('swipt_code'))
                                    <span class="text-danger">{{$errors->first('swipt_code')}}</span>
                                @endif
                            </div>
                            <div class="media">
                                <label class="col-form-label m-r-10">Bank Details Active</label>
                                <div class="media-body text-right">
                                    <label class="switch">
                                        <input type="hidden" name="status" value="off">
                                        @if($bank_details->status == 1)
                                        <input type="checkbox" checked="" name="status" valus="on">
                                        @else
                                        <input type="checkbox" name="status" valus="off">
                                        @endif
                                        <span class="switch-state"></span>
                                    </label>
                                </div>
                            </div>
                            <!-- <div class="form-group col-md-12">
                                <p class="text-info"><b>Note:</b> Please give correct transaction id details.</p>
                            </div> -->
                            <div class="form-group col-md-12 text-right">
                                <button type="submit" class="btn btn-success mt-4" id="paypal-btn">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

@section('script')
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
// just for the demos, avoids form submit

$( "#W-form" ).validate({
  rules: {
    account_no: {
      required: true,
      digits: true
    }
  }
});
</script>

@endsection

resources/views/admin/edit_phase.blade.php
@extends('dashboard_layouts.master')


@section('title') Edit Phase | Vancoin @endsection

@section('style')
    <!-- DatePicker css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/date-picker.css') }}">
@endsection()

@section('content')

<div class="page-body">
    <!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Edit Phase
                        <small>Vancoin Admin panel</small>
                    </h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Edit Phase</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-xl-6">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Phase Information</h5>
                            </div>
                            <form method="post" action="{{ url('do-edit-phase') }}" class="theme-form mega-form">
                                {{ csrf_field() }}
                                <div class="card-body">
                                    <input type="hidden" name="phase_id" value="{{ $phase->id }}">
                                    <div class="form-group">
                                        <label class="col-form-label">Phase Name</label>
                                        <input type="text" name="phase_name" class="form-control" placeholder="phase name" value="{{ $phase->phase_name }}">
                                        @if($errors->has('phase_name'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('phase_name') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label  class="col-form-label">USD Price</label>
                                        <input type="text" name="usd_price" class="form-control" placeholder="Enter price in USD" value="{{ $phase->usd_price }}">
                                        @if($errors->has('usd_price'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('usd_price') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">VCoin</label>
                                        <input type="text" name="total_coins" class="form-control" placeholder="enter solding coins" value="{{ $phase->total_coins }}">
                                        @if($errors->has('total_coins'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('total_coins') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Bonus</label>
                                        <input type="text" name="bonus" class="form-control" placeholder="bonus coins" value="{{ $phase->bonus }}">
                                        @if($errors->has('bonus'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('bonus') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">Start Date</label>
                                        <?php
                                            $start_date = $phase->start_date;
                                            $new_start_date = date("d/m/Y", strtotime($start_date));
                                        ?>

                                        <input type="text" name="start_date" data-language="en" class="form-control datepicker-here digits" aria-describedby="basic-addon2" value="{{ $new_start_date }}">

                                        @if($errors->has('start_date'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('start_date') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        <label class="col-form-label">End Date</label>
                                        <?php
                                            $end_date = $phase->end_date;
                                            $new_end_date = date("d/m/Y", strtotime($end_date));
                                        ?>

                                        <input type="text" name="end_date" data-language="en" class="form-control datepicker-here digits" aria-describedby="basic-addon2" value="{{ $new_end_date }}">

                                        @if($errors->has('end_date'))
                                        <span class="text-danger">
                                            <strong>{{ $errors->first('end_date') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary">Submit</button>
                                    <a href="{{ url('phases') }}" class="btn btn-danger">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<!--DateTime Picker js-->
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.js') }}"></script>
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.en.js') }}"></script>
<script src="{{ URL::asset('/assets/back/js/date-picker/datepicker.custom.js') }}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#dashboard-table').DataTable();
} );
</script>
@endsection