routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/','HomeController@home');
Route::get('/home','HomeController@home');
Route::get('news','HomeController@news_page');
Route::get('blogs','HomeController@blog_page');
Route::get('contact-us','HomeController@contact_us');
Route::get('news/{id}','HomeController@news');
Route::get('blog/{id}','HomeController@blog');


Route::get('Ccavenue','CCAvenueController@index');
Route::post('Ccavenue','CCAvenueController@Ccavenue');

// Registration and Activation
Route::view('register','home_pages.registration');
Route::post('postregister','RegistrationController@postRegister');
Route::get('activate/{email}/{code}','RegistrationController@activateMail');


// User Login
Route::get('login','LoginController@login');
Route::post('do-user-login','LoginController@vcoinLogin');
Route::get('do-user-logout','LoginController@dologout');

// Forgot Password
Route::get('forgot-password','LoginController@forgot_password');
Route::post('check-email','LoginController@check_email');
Route::get('reset-password/{email}/{token}','LoginController@reset_password');
Route::post('do-reset-password','LoginController@do_reset_password');


// ipn handler
// Route::post('ipn-handler','DepositController@IpnHandler');
Route::get('ipn-handler','DepositController@IpnHandler');
Route::post('withdrawal-handler','UserController@withdrawal_IpnHandler');
// User Routes
Route::group(['middleware' => 'user'],function(){

	Route::get('user-dashboard','DashboardController@user_dashboard');
	//user profile change password
	Route::get('user-profile','ProfileController@user_profile');
	Route::post('update-user-profile','ProfileController@update_user_profile');
	Route::post('change-password','ProfileController@change_password');
	Route::post('profile_update','ProfileController@profile_update');
	//user kyc
	// Route::get('user-kyc','KycController@index');
	// Route::post('user-kyc-upload','KycController@kyc_upload');
	//user wallet
	Route::get('user-wallet','UserController@user_wallet');
	Route::get('deposit/{coin}','DepositController@deposit');
	Route::get('withdraw/{coin}','UserController@withdraw');
	Route::post('do-withdraw','UserController@do_withdraw');
	//deposit bank
	Route::get('deposit-bank','UserController@bankDeposit');
	Route::post('amount-deposit-bank','UserController@amountDepositBank');
	//withdrawal bank
	// Route::get('withdraw-bank','UserController@bankWithdrawal');
	// Route::post('amount-withdrawal-bank','UserController@amountWithdrawalBank');

	// ico / buy-token
	Route::get('buy-token-list','BuyTokenController@icoInformation');
	Route::post('coin-balance','BuyTokenController@coinBalance');
	Route::post('buy-token/{id}','BuyTokenController@buyToken');

	Route::get('ico-information','UserController@ico_information');
	Route::get('network','UserController@network');
	Route::get('getUserDataNetwork','UserController@getUserDataNetwork');
	// buy with paypal
	Route::post('buy-paypal','PaypalController@postPaymentWithpaypal');
	Route::get('success-payment','PaypalController@paymentSucces');
	Route::get('cancel-payment','PaypalController@paymentCancel');
	Route::post('cancel-payment','PaypalController@paymentCancel');
	Route::get('callback','PaypalController@paypalCallback');
	Route::post('currency-price','PaypalController@currencyPrice');
	

});
// User Login

//Route::get('administrator','LoginController@login');
Route::post('do-admin-login','LoginController@dologin');
Route::get('do-admin-logout','LoginController@dologout');

// Admin Routes
Route::group(['middleware' => 'admin'],function(){
	// dashboard
	Route::get('admin-dashboard','DashboardController@admin_dashboard');
	// user manage
	Route::get('user-manage','AdminController@user_manage');
	Route::get('user-status/{id}','AdminController@userStatus');
	Route::get('user-delete/{id}','AdminController@userDelete');
	// profile
	Route::get('admin-profile','ProfileController@user_profile');
	Route::post('update-admin-profile','ProfileController@update_user_profile');
	Route::post('admin-change-password','ProfileController@change_password');
	Route::post('admin-profile-update','ProfileController@profile_update');
	// user kyc approve and regect
	// Route::get('kyc/{id}','AdminController@userKyc');
	// Route::get('kyc-approve/{id}','AdminController@kyc_approve');
	// Route::get('kyc-reject/{id}','AdminController@kyc_reject');
	// history
	Route::get('deposit-history','HistoryController@depositHistory');
	Route::get('withdraw-history','HistoryController@withdrawHistory');
	Route::get('token-history','HistoryController@tokenHistory');
	// setting ico
	Route::get('settings','SettingController@settings');
	Route::post('update-settings','SettingController@update_settings');

	Route::get('phases','PhaseController@phases');
	Route::get('add-phase','PhaseController@add_phase');
	Route::post('do-add-phase','PhaseController@do_add_phase');
	Route::get('edit-phase/{id}','PhaseController@edit_phase');
	Route::post('do-edit-phase','PhaseController@do_edit_phase');
	Route::get('do-delete-phase/{id}','PhaseController@do_delete_phase');
	Route::get('do-active-phase/{id}','PhaseController@do_active_phase');
	// Withdrawal
	Route::get('withdraw-manage','WithdrawalController@withdraw_manage');
	Route::get('withdraw-approval/{id}','WithdrawalController@withdraw_approval');
	Route::get('withdraw-reject/{id}','WithdrawalController@withdraw_reject');
	//withdrawal bank
	// Route::get('withdraw-approval-bank/{id}','WithdrawalController@withdrawBank');
	// Route::post('withdraw-approval-bank/{id}','WithdrawalController@withdrawApproveBank');
	// Route::get('withdraw-reject-bank/{id}','WithdrawalController@withdrawRejectBank');
	//bank
	Route::resource('bank-details','BankDetailsController');
	//deposit bank
	Route::get('deposit-approve-bank/{id}','DepositController@approveddepositBank');
	Route::get('deposit-reject-bank/{id}','DepositController@rejecteddepositBank');



	// News
	Route::resource('news-manage','NewsController');
	Route::resource('blog-manage','BlogController');

});

Route::get('exchange','PaypalController@currency');
//google2fa
Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
Route::post('/2fa/save', 'Google2FAController@saveSecretKey');
Route::post('/2fa/disable', 'Google2FAController@disableTwoFactor');
Route::get('/2fa/validate', 'Auth\AuthController@getValidateToken');
Route::post('/2fa/validate', ['uses' => 'Auth\AuthController@postValidateToken']);
Route::post('/2fa/validate-disabletime', ['uses' => 'Auth\AuthController@postValidateTokenDesable']);
Route::post('2fa/validate-enabletime', 'Auth\AuthController@postValidateTokenenable');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    //
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blog = Blog::orderBy('id','desc')->get();
        return view('admin.blogs.blog-index',compact('blog'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request,[
        'title' =>  'required',
        'content' => 'required',
        'img' =>  'required|mimes:jpeg,png,jpg,gif,svg'  
       ]);

        $image = $request->file('img');
        $img_name = rand(11111, 99999);
        $path = public_path('/assets/back/blog/');
        $image->move($path, $img_name);

        $blog = new Blog;
        $blog->title = $request->title;
        $blog->sub_title = $request->sub_title;
        $blog->content = $request->content;
        $blog->img = $img_name;
        $blog->link = $request->link;
        $blog->save();

        $notification = array(
            'message' => 'Successfull created blog.', 
            'alert-type' => 'success'
        );
        return redirect('blog-manage')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog,$id)
    {
        $blog = Blog::find($id);
        return view('admin.blogs.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Blog $blog, $id)
    {
        $this->validate($request,[
            'title' =>  'required',
            'content' =>  'required'
        ]);

        $blog = Blog::find($id);
        $blog->title = $request->title;
        $blog->sub_title = $request->sub_title;
        $blog->content = $request->content;
        $blog->link = $request->link;

        if ($request->file('img')) {
            try{
            $file_path = public_path().'/assets/back/blog/'.$blog->img;
            unlink($file_path);
                }
            catch (\ErrorException  $e) {
            // return $e->getMessage();
            }

            $image = $request->file('img');
            $img_name = rand(11111, 99999).'_'.$image->getClientOriginalName();
            $path = public_path('/assets/back/blog/');
            $image->move($path, $img_name);
            $blog->img = $img_name;
        }

        $blog->save();

        $notification = array(
            'message' => 'Successfull updated blog.', 
            'alert-type' => 'success'
        );
        return redirect('blog-manage')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog,$id)
    {
        $blog = Blog::find($id);
        $blog->delete();

        $notification = array(
            'message' => 'Successfull deleted blog.', 
            'alert-type' => 'success'
        );
        return redirect('blog-manage')->with($notification);
    }
}

resources/views/admin/blogs/blog-index.blade.php
@extends('dashboard_layouts.master')

@section('title') Blogs Manage | Vancoin @endsection

@section('content')

<div class="page-body">
    <!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Blogs Manage</h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Setting</li>
                        <li class="breadcrumb-item active">Blogs Manage</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
            	<a href="{{ route('blog-manage.create') }}" title="Latest blog Add" class="btn btn-primary">Add Blogs</a>
            </div>
            <div class="card-body table-responsive" data-intro="This is the name of this site">
                <div class="user-status">
                    <table id="blog-table" class="display" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Title</th>
                                <th>Sub Title</th>
                                <th>Content</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@php $i=1; @endphp
                        	@foreach($blog as $blo)
                        		<tr>
                        			<td>{{ $i++ }}</td>
                        			<td>{{ $blo->title }}</td>
                        			<td>{{ $blo->sub_title }}</td>
                        			<td>{!! substr($blo["content"], 0, 340) !!}</td>
                        			<td><img src="{{ URL::asset('assets/back/blog') }}/{{ $blo->img }}" height="40px" width="40px" alt=""></td>
                        			<td><a href="{{ route('blog-manage.edit',$blo->id) }}" title="Edit" class="btn btn-info">Edit</a>
                        				<form action="{{ route('blog-manage.destroy',$blo->id) }}" method="post" accept-charset="utf-8">
                        					{{ csrf_field() }}
                        					{{ method_field('DELETE') }}
                        					<button type="delete" class="btn btn-danger mt-2">Delete</button>
                        				</form>
                        			</td>
                        		</tr>
                        	@endforeach                        	
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
	    $('#blog-table').DataTable();
	} );
	</script>
@endsection

resources/views/admin/blogs/create.blade.php
@extends('dashboard_layouts.master')


@section('title') Blogs Manage | Vancoin @endsection

@section('content')
<div class="page-body">
<!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Add New Blogs
                        <!-- <small>Vancoin Admin panel</small> -->
                    </h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Add New Blogs</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends -->

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Add Latest Blogs</h5>
                    </div>
                    <form method="post" action="{{ route('blog-manage.store') }}" class="theme-form mega-form" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="card-body">
                            <div class="form-group">
                                <label class="col-form-label">Title</label>
                                <input type="text" name="title" class="form-control" placeholder="Enter Blogs Title..." >
                                @if($errors->has('title'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label  class="col-form-label">Sub Title</label>
                                <input type="text" name="sub_title" class="form-control" placeholder="Enter Blogs Sub Title...">
                                @if($errors->has('sub_title'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('sub_title') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Content</label>
                                <textarea name="content" class="form-control" id="editor1" cols="20" rows="15" value="{{ old('content') }}">{{ old('content') }}</textarea>
                                @if($errors->has('content'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('content') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Image</label>
                                <input type="file" name="img" class="form-control">
                                @if($errors->has('img'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('img') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Link</label>
                                <input type="text" name="link" class="form-control">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary">Submit</button>
                            <a href="{{ url('blog-manage') }}" class="btn btn-danger">Cancel</a>
                        </div>
                    </form>
                </div>                    
            </div>
        </div>
    </div>

 </div>

@endsection

@section('script')
<script src="{{ URL::asset('assets/back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/styles.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/adapters/jquery.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/ckeditor.custom.js') }}"></script>
@endsection

resources/views/admin/blogs/edit.blade.php
@extends('dashboard_layouts.master')


@section('title') Blogs Manage | Vancoin @endsection

@section('content')
<div class="page-body">
<!-- Container-fluid starts -->
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <h3>Edit Blogs
                        <!-- <small>Vancoin Admin panel</small> -->
                    </h3>
                </div>
                <div class="col-lg-6" data-intro="This is the name of this site">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Edit Blogs</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends -->

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Edit Blogs</h5>
                    </div>
                  <form method="POST" action="{{ route('blog-manage.update',$blog->id) }}" class="theme-form mega-form" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="card-body">
                            <div class="form-group">
                                <label class="col-form-label">Title</label>
                                <input type="text" name="title" class="form-control" value="{{ $blog->title }}" placeholder="Enter Blog Title..." >
                                @if($errors->has('title'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label  class="col-form-label">Sub Title</label>
                                <input type="text" name="sub_title" class="form-control" value="{{ $blog->sub_title }}" placeholder="Enter Blog Sub Title...">
                                @if($errors->has('sub_title'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('sub_title') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Content</label>
                                <textarea name="content" class="form-control" id="editor1" cols="20" rows="15" value="{{ $blog->content }}">{{ $blog->content }}</textarea>
                                @if($errors->has('content'))
                                <span class="text-danger">
                                    <strong>{{ $errors->first('content') }}</strong>
                                </span>
                                @endif
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Image</label>
                                <img src="{{ URL::asset('assets/back/blog') }}/{{ $blog->img }}" alt="" height="100px" width="100px">
                                <input type="file" name="img">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label">Link</label>
                                <input type="text" name="link" class="form-control" value="{{ $blog->link }}">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-primary">Submit</button>
                            <a href="{{ url('blog-manage') }}" class="btn btn-danger">Cancel</a>
                        </div>
                    </form>
                </div>                    
            </div>
        </div>
    </div>

 </div>

@endsection

@section('script')
<script src="{{ URL::asset('assets/back/js/ckeditor/ckeditor.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/styles.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/adapters/jquery.js') }}"></script>
<script src="{{ URL::asset('assets/back/js/ckeditor/ckeditor.custom.js') }}"></script>
@endsection