routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/','HomeController@home');
Route::get('/home','HomeController@home');
Route::get('news','HomeController@news_page');
Route::get('blogs','HomeController@blog_page');
Route::get('contact-us','HomeController@contact_us');
Route::get('news/{id}','HomeController@news');
Route::get('blog/{id}','HomeController@blog');


Route::get('Ccavenue','CCAvenueController@index');
Route::post('Ccavenue','CCAvenueController@Ccavenue');

// Registration and Activation
Route::view('register','home_pages.registration');
Route::post('postregister','RegistrationController@postRegister');
Route::get('activate/{email}/{code}','RegistrationController@activateMail');


// User Login
Route::get('login','LoginController@login');
Route::post('do-user-login','LoginController@vcoinLogin');
Route::get('do-user-logout','LoginController@dologout');

// Forgot Password
Route::get('forgot-password','LoginController@forgot_password');
Route::post('check-email','LoginController@check_email');
Route::get('reset-password/{email}/{token}','LoginController@reset_password');
Route::post('do-reset-password','LoginController@do_reset_password');


// ipn handler
// Route::post('ipn-handler','DepositController@IpnHandler');
Route::get('ipn-handler','DepositController@IpnHandler');
Route::post('withdrawal-handler','UserController@withdrawal_IpnHandler');
// User Routes
Route::group(['middleware' => 'user'],function(){

	Route::get('user-dashboard','DashboardController@user_dashboard');
	//user profile change password
	Route::get('user-profile','ProfileController@user_profile');
	Route::post('update-user-profile','ProfileController@update_user_profile');
	Route::post('change-password','ProfileController@change_password');
	Route::post('profile_update','ProfileController@profile_update');
	//user kyc
	// Route::get('user-kyc','KycController@index');
	// Route::post('user-kyc-upload','KycController@kyc_upload');
	//user wallet
	Route::get('user-wallet','UserController@user_wallet');
	Route::get('deposit/{coin}','DepositController@deposit');
	Route::get('withdraw/{coin}','UserController@withdraw');
	Route::post('do-withdraw','UserController@do_withdraw');
	//deposit bank
	Route::get('deposit-bank','UserController@bankDeposit');
	Route::post('amount-deposit-bank','UserController@amountDepositBank');
	//withdrawal bank
	// Route::get('withdraw-bank','UserController@bankWithdrawal');
	// Route::post('amount-withdrawal-bank','UserController@amountWithdrawalBank');

	// ico / buy-token
	Route::get('buy-token-list','BuyTokenController@icoInformation');
	Route::post('coin-balance','BuyTokenController@coinBalance');
	Route::post('buy-token/{id}','BuyTokenController@buyToken');

	Route::get('ico-information','UserController@ico_information');
	Route::get('network','UserController@network');
	Route::get('getUserDataNetwork','UserController@getUserDataNetwork');
	// buy with paypal
	Route::post('buy-paypal','PaypalController@postPaymentWithpaypal');
	Route::get('success-payment','PaypalController@paymentSucces');
	Route::get('cancel-payment','PaypalController@paymentCancel');
	Route::post('cancel-payment','PaypalController@paymentCancel');
	Route::get('callback','PaypalController@paypalCallback');
	Route::post('currency-price','PaypalController@currencyPrice');
	

});
// User Login

//Route::get('administrator','LoginController@login');
Route::post('do-admin-login','LoginController@dologin');
Route::get('do-admin-logout','LoginController@dologout');

// Admin Routes
Route::group(['middleware' => 'admin'],function(){
	// dashboard
	Route::get('admin-dashboard','DashboardController@admin_dashboard');
	// user manage
	Route::get('user-manage','AdminController@user_manage');
	Route::get('user-status/{id}','AdminController@userStatus');
	Route::get('user-delete/{id}','AdminController@userDelete');
	// profile
	Route::get('admin-profile','ProfileController@user_profile');
	Route::post('update-admin-profile','ProfileController@update_user_profile');
	Route::post('admin-change-password','ProfileController@change_password');
	Route::post('admin-profile-update','ProfileController@profile_update');
	// user kyc approve and regect
	// Route::get('kyc/{id}','AdminController@userKyc');
	// Route::get('kyc-approve/{id}','AdminController@kyc_approve');
	// Route::get('kyc-reject/{id}','AdminController@kyc_reject');
	// history
	Route::get('deposit-history','HistoryController@depositHistory');
	Route::get('withdraw-history','HistoryController@withdrawHistory');
	Route::get('token-history','HistoryController@tokenHistory');
	// setting ico
	Route::get('settings','SettingController@settings');
	Route::post('update-settings','SettingController@update_settings');

	Route::get('phases','PhaseController@phases');
	Route::get('add-phase','PhaseController@add_phase');
	Route::post('do-add-phase','PhaseController@do_add_phase');
	Route::get('edit-phase/{id}','PhaseController@edit_phase');
	Route::post('do-edit-phase','PhaseController@do_edit_phase');
	Route::get('do-delete-phase/{id}','PhaseController@do_delete_phase');
	Route::get('do-active-phase/{id}','PhaseController@do_active_phase');
	// Withdrawal
	Route::get('withdraw-manage','WithdrawalController@withdraw_manage');
	Route::get('withdraw-approval/{id}','WithdrawalController@withdraw_approval');
	Route::get('withdraw-reject/{id}','WithdrawalController@withdraw_reject');
	//withdrawal bank
	// Route::get('withdraw-approval-bank/{id}','WithdrawalController@withdrawBank');
	// Route::post('withdraw-approval-bank/{id}','WithdrawalController@withdrawApproveBank');
	// Route::get('withdraw-reject-bank/{id}','WithdrawalController@withdrawRejectBank');
	//bank
	Route::resource('bank-details','BankDetailsController');
	//deposit bank
	Route::get('deposit-approve-bank/{id}','DepositController@approveddepositBank');
	Route::get('deposit-reject-bank/{id}','DepositController@rejecteddepositBank');



	// News
	Route::resource('news-manage','NewsController');
	Route::resource('blog-manage','BlogController');

});

Route::get('exchange','PaypalController@currency');
//google2fa
Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
Route::post('/2fa/save', 'Google2FAController@saveSecretKey');
Route::post('/2fa/disable', 'Google2FAController@disableTwoFactor');
Route::get('/2fa/validate', 'Auth\AuthController@getValidateToken');
Route::post('/2fa/validate', ['uses' => 'Auth\AuthController@postValidateToken']);
Route::post('/2fa/validate-disabletime', ['uses' => 'Auth\AuthController@postValidateTokenDesable']);
Route::post('2fa/validate-enabletime', 'Auth\AuthController@postValidateTokenenable');

resources/views/dashboard_layouts/footer_script.blade.php
<!-- latest jquery-->
<script src="{{ URL::asset('/assets/back/js/jquery-3.2.1.min.js') }}" ></script>
<!-- Bootstrap js-->
<script src="{{ URL::asset('/assets/back/js/bootstrap/popper.min.js') }}" ></script>
<script src="{{ URL::asset('/assets/back/js/bootstrap/bootstrap.js') }}" ></script>
<!-- Chart JS-->
<script src="{{ URL::asset('/assets/back/js/chart/Chart.min.js') }}"></script>
<!-- candile-chart js-->
<script src="{{ URL::asset('/assets/back/js/chart/candile-chart/amcharts.js') }}" ></script>
<!-- <script src="{{ URL::asset('/assets/back/js/chart/candile-chart/candile.all.js') }}" ></script> -->
<script src="{{ URL::asset('/assets/back/js/chart/candile-chart/serial.js') }}" ></script>
<script src="{{ URL::asset('/assets/back/js/chart/candile-chart/candile-script.js') }}" ></script>
<!-- Morris Chart JS-->
<script src="{{ URL::asset('/assets/back/js/chart/morris-chart/raphael.js') }}"></script>
<script src="{{ URL::asset('/assets/back/js/chart/morris-chart/morris.js') }}"></script>
<!-- owlcarousel js-->
<script src="{{ URL::asset('/assets/back/js/owlcarousel/owl.carousel.js') }}" ></script>
<!-- Sidebar jquery-->
<script src="{{ URL::asset('/assets/back/js/sidebar-menu.js') }}" ></script>
<!--Sparkline  Chart JS-->
<script src="{{ URL::asset('/assets/back/js/chart/sparkline/sparkline.js') }}"></script>
<!-- tour js -->
<!-- <script src="{{ URL::asset('/assets/back/js/tour/intro.js') }}" ></script> -->
<!-- <script src="../assets/js/tour/intro-init.js" ></script> -->
<!-- Theme js-->
<script src="{{ URL::asset('/assets/back/js/script.js') }}" ></script>
<!-- <script src="{{ URL::asset('/assets/back/js/dashboard-default.js') }}" ></script> -->
<!-- main theme customizer js -->
<!-- <script src="{{ URL::asset('/assets/back/js/theme-customizer/customizer.js') }}"></script> -->
<!-- Toastr Mesage -->
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script> -->
<!-- datatable  -->
<script src="{{ URL::asset('/assets/back/js/datatables/jquery.dataTables.min.js') }}"></script>
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script> -->
<!-- datatable  -->

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script src='{{ URL::asset("assets/back/js/toastr.min.js") }}' type='text/javascript'></script> 
<!-- InstantClick -->
<!-- <script src="{{ URL::asset('/assets/back/js/instantclick.js') }}" data-no-instant></script>
<script data-no-instant>InstantClick.init();</script> -->

<script>
  @if(Session::has('message'))
    var type = "{{ Session::get('alert-type', 'info') }}";
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;

        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;

        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
  @endif
</script>

<script>
    // active link
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className += ' active';
        document.links[i].parentElement.parentElement.parentElement.className += ' active';
    }
}
</script>

resources/views/dashboard_layouts/head.blade.php
 <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/fontawesome.css') }}">
    <!-- iconfont -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/icofont.css') }}">
    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/themify.css') }}">
    <!-- Flag icon -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/flag-icon.css') }}">
    <!-- Tour css -->
    <!-- <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/tour.css') }}"> -->
    <!-- Owl css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/owlcarousel.css') }}">
    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/bootstrap.css') }}">
    <!-- App css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/style.css') }}">
    <!-- Responsive css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/responsive.css') }}">
    <!-- datatble css -->
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('/assets/back/css/datatables.css') }}">
    <!-- Toastr message -->
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">\

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">

resources/views/dashboard_layouts/header.blade.php
<?php
    $slug = Sentinel::getUser()->roles()->first()->slug;
?>
<div class="page-main-header">
    <div class="main-header-left">
        <div class="logo-wrapper">
            <a href="{{ url('/home') }}">
                <img src="{{ URL::asset('assets/home/images/logo.png') }}"  alt=""/>
            </a>
        </div>
    </div>
    <div class="main-header-right row">
        <div class="mobile-sidebar">
            <div class="media-body text-right switch-sm">
                <label class="switch">
                    <input type="checkbox" id="sidebar-toggle" checked>
                    <span class="switch-state"></span>
                </label>
            </div>
        </div>
        <div class="nav-right col">
            <ul class="nav-menus">
                <!--  @if(Sentinel::getUser()->roles()->first()->slug == 'user')
                <div class="col-lg-4" style="margin-top: 18px;">
                      <form class="form-copy theme-form">
                          <div class="form-group">
                              <div class="input-group">                                
                                  <input type="text" id="copy" class="form-control" value="{{url('/register')}}/?referral_code={{ Sentinel::getUser()->referral_code }}" readonly="" aria-label="Search for...">
                                 <span class="input-group-btn">
                                 <button class="btn btn-success" type="button" data-copytarget="#lets_copy" onclick="copyFunction()" title="Copy"><i class="fa fa-copy" style="font-size:30;"></i></button>
                                 </span>
                              </div>
                          </div>
                      </form>
                  </div>
                  @endif -->
                <li class="onhover-dropdown">
                    <div class="media  align-items-center">
                        <img class="align-self-center pull-right mr-2" src="{{ URL::asset('assets/back/images/dashboard/user.png') }}" alt="header-user"/>
                        <div class="media-body">
                            <h6 class="m-0 txt-dark f-16">
                                My Account
                                <i class="fa fa-angle-down pull-right ml-2"></i>
                            </h6>
                        </div>
                    </div>
                    
                    <ul class="profile-dropdown onhover-show-div p-20">
                        @if($slug == 'user')
                        <li>
                            <a href="{{url('user-profile')}}">
                                <i class="icon-user"></i>
                                Edit Profile
                            </a>
                        </li>
                        @else
                        <li>
                            <a href="{{url('admin-profile')}}">
                                <i class="icon-user"></i>
                                Edit Profile
                            </a>
                        </li>
                        @endif
                        
                        <li>
                            
                            @if($slug == 'admin')
                                <a href="{{url('do-admin-logout')}}">
                                    <i class="icon-power-off"></i>
                                    Logout
                                </a>
                            @else
                                <a href="{{url('do-user-logout')}}">
                                    <i class="icon-power-off"></i>
                                    Logout
                                </a>
                            @endif
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="d-lg-none mobile-toggle">
                <i class="icon-more"></i>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function copyFunction() {
    /* Get the text field */
    var copyText = document.getElementById("copy");
    /* Select the text field */
    copyText.select();
    /* Copy the text inside the text field */
    document.execCommand("copy");
  }


</script>

resources/views/dashboard_layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="universal admin is super flexible, powerful, clean & modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, universal admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="{{ URL::asset('/assets/home/images/favicon.png') }}" type="image/x-icon"/>
    <link rel="shortcut icon" href="{{ URL::asset('/assets/home/images/favicon.png') }}" type="image/x-icon"/>
    <title>@yield('title')</title>

    @include('dashboard_layouts.head')

    @yield('style')
</head>
<body>

	<div class="page-wrapper">

		@include('dashboard_layouts.header')
		
		<div class="page-body-wrapper">

			@include('dashboard_layouts.sidebar')

			@yield('content')
		
		</div>
	</div>

	@include('dashboard_layouts.footer_script')
	
	@yield('script')
</body>
</html>

resources/views/dashboard_layouts/sidebar.blade.php
<!-- page sidebar -->
<?php
    $slug = Sentinel::getUser()->roles()->first()->slug;
?>

<div class="page-sidebar custom-scrollbar">
    <div class="sidebar-user text-center">
        <div>
            @if(Sentinel::getUser()->profile_pic != "")
                <img class="img-50 rounded-circle" src="{{ url('assets/back/profile/'.Sentinel::getUser()->profile_pic) }}" alt="user">
            @else
                <img class="img-50 rounded-circle" src="{{ URL::asset('/assets/back/images/avtar/1.jpg') }}" alt="user">
            @endif
        </div>
        <h6 class="mt-3 f-12">{{Sentinel::getUser()->user_name}}</h6>
    </div>
    @if($slug == 'user')
    <ul class="sidebar-menu">

        <div class="sidebar-title">General</div>
        <li>
            <a href="{{ url('user-dashboard') }}" class="sidebar-header" class="active">
                <i class="icon-blackboard"></i> <span>Dashboard</span>
            </a>
        </li>
        <!-- <li>
            <a href="{{ url('user-kyc') }}" class="sidebar-header">
                <i class="fa fa-id-card-o" aria-hidden="true"></i><span>Kyc Document</span>
            </a>
        </li> -->
        <li>
            <div class="sidebar-title">ICO</div>
            <a href="#" class="sidebar-header">
                <i class="fa fa-eercast" aria-hidden="true"></i><span>ico</span>
                <i class="fa fa-angle-right pull-right"></i>
            </a>
            <ul class="sidebar-submenu">

                <li><a href="{{ url('ico-information') }}"><i class="fa fa-angle-right"></i>ICO Information</a></li>
                <li><a href="{{ url('buy-token-list') }}"><i class="fa fa-angle-right"></i>Buy token</a></li>
            </ul>
        </li>
         <li>
            <a href="{{ url('user-wallet') }}" class="sidebar-header">
                <i class="icon-credit-card"></i><span>Wallet</span>
            </a>
        </li>
        <!-- <li>
            <a href="{{ url('network') }}" class="sidebar-header">
                <i class="fa fa-sitemap" aria-hidden="true"></i><span>Network</span>
            </a>
        </li>   -->      
    </ul>
    <div class="sidebar-widget text-center">
       <div class="sidebar-widget-top">
           <h6 class="mb-2 fs-14">Need Help</h6>
           <i class="fa fa-bell"></i>
       </div>
       <div class="sidebar-widget-bottom p-20 m-20">
           <p>(713)898-6818 ( USA)
               <br>vanjiagroup@gmail.com
               <br>Contact With VNJA
           </p>
       </div>
   </div>
    @elseif($slug == 'admin')
    <ul class="sidebar-menu">
        <div class="sidebar-title">General</div>
        <li>
            <a href="{{ url('admin-dashboard') }}" class="sidebar-header" class="active">
                <i class="icon-blackboard"></i> <span>Dashboard</span>
            </a>
        </li>
        <div class="sidebar-title">Management</div>
        <li>
            <a href="{{ url('user-manage') }}" class="sidebar-header">
                <i class="icon-user"></i><span>Users</span>
            </a>
        </li>
        <li>

            <a href="{{ url('withdraw-manage') }}" class="sidebar-header">
                <i class="icon-credit-card"></i><span>Withdrwal</span>

            </a>
        </li>
        <!-- <li>
            <a href="#" class="sidebar-header">
                <i class="icon-credit-card"></i><span>Transfer Token</span>
            </a>
        </li> -->
        <div class="sidebar-title"><i class="fa fa-history" aria-hidden="true"></i> Historys</div>
        <li>
            <a href="{{ url('deposit-history') }}" class="sidebar-header">
                <i class="fa fa-clock-o" aria-hidden="true"></i><span>Deposit History</span>
            </a>
        </li>
        <li>
            <a href="{{ url('withdraw-history') }}" class="sidebar-header">
                <i class="fa fa-clock-o" aria-hidden="true"></i><span>withdraw History</span>
            </a>
        </li>
        <li>
            <a href="{{ url('token-history') }}" class="sidebar-header">
                <i class="fa fa-clock-o" aria-hidden="true"></i><span>Token History</span>
            </a>
        </li>
        <div class="sidebar-title">Settings</div>
        <li>
            <a href="{{ url('settings') }}" class="sidebar-header">
                <i class="icon-settings"></i><span>Settings</span>
            </a>
        </li>
        <li>
            <a href="{{ url('phases') }}" class="sidebar-header">
                <i class="icon-ruler"></i><span>Phase Settings</span>
            </a>
        </li> 
        <li>
            <a href="{{ route('news-manage.index') }}" class="sidebar-header">
                <i class="fa fa-newspaper-o" aria-hidden="true"></i><span>News Feed</span>
            </a>
        </li>
        <li>
            <a href="{{ route('blog-manage.index') }}" class="sidebar-header">
                <i class="fa fa-newspaper-o" aria-hidden="true"></i><span>Blogs Feed</span>
            </a>
        </li>
        <li>
            <a href="{{ route('bank-details.index') }}" class="sidebar-header">
                <i class="fa fa-university" aria-hidden="true"></i><span>Bank Details</span>
            </a>
        </li>       
    </ul>
    @endif
</div>
<!--End page sidebar -->